# 事件派发监听

## 问题

- [x] 创建实例
- [x] 事件监听，注册回调
- [x] 事件派发
- [x] 移除监听事件
- [x] 事件触发一次
- [x] 错误处理

## Events 模块

所有能够监听派发事件的对象都是 `EventEmitter` 类的实例。

### API

emitter 是实例方法

- emitter.emit
- emitter.on 别名 emitter.addListener
- emitter.off 别名 emitter.removeListener
- emitter.once

### 🌰

`EventEmitter` 对象的事件触发和监听是同步的。

```js
const EventEmitter = require('events');

class WithLog extends EventEmitter {
  execute(taskFunc) {
    console.log('Before executing');
    this.emit('begin');
    taskFunc();
    this.emit('end');
    console.log('After executing');
  }
}

const withLog = new WithLog();

withLog.on('begin', () => console.log('About to execute'));
withLog.on('end', () => console.log('Done with execute'));

withLog.execute(() => console.log('*** Executing task ***'));

// 执行结果
Before executing
About to execute
*** Executing task ***
Done with execute
After executing
```

当没有 `error` 事件的处理程序，一个 `error` 事件被派发，错误会被抛出，Node 程序终止，作为最佳实践，需要给 `error` 实践注册一个处理程序。

```js
const myEmitter = new MyEmitter();
myEmitter.on('error', (err) => {
  console.error('whoops! there was an error');
});
myEmitter.emit('error', new Error('whoops!'));
// Prints: whoops! there was an error
```

## 参考

- [Events](https://nodejs.org/dist/latest-v12.x/docs/api/events.html)
- [Understanding Node.js Event-Driven Architecture](https://www.freecodecamp.org/news/understanding-node-js-event-driven-architecture-223292fcbc2d/)
